### ISSUE TITLE
Cancel/Close User Options Modal Throws Error

### ISSUE THREAD

**Issue by timcortesi** [EscherLabs/Graphene#10]
The user options modal seems to throw an error when the modal is closed (Cancel button or X in the top right corner)
```
}).on('cancel',function(e){
    e.form.pub('close')
})
```
> TypeError: e.form.pub is not a function

**Comment by Cloverstone** [comment]
i believe the code i pushed earlier addressed this one, are you using that code?

**Comment by timcortesi** [comment]
This error is showing up in the latest version of the code.  Example:

https://my.binghamton.edu/app/MAIN/universalsearch
The error is being thrown by the javascript running directly on the page.
