### ISSUE TITLE
Graphene Forms: Default Date Strings for "date" field types don't behave as expected

### ISSUE THREAD

**Issue by timcortesi** [EscherLabs/Graphene#100]
It doesn't look like Graphene Form `date` types handle default values correctly.  See the example below:
```json
{
	"type": "date",
	"label": "Requested Start Date",
	"name": "start_date",
	"value": "01/04/2021",
	"columns": 6,
	"required": true,
	"format": {
		"input": "MM/DD/YYYY"
	}
}
```
I would expect it to auto-populate that field to this:
<img width="406" alt="Screen Shot 2020-12-21 at 1 28 54 PM" src="https://user-images.githubusercontent.com/5395437/102809729-84f60780-4390-11eb-9e4a-6395dba5bb50.png">

Instead, I'm seeing a blank field:
<img width="402" alt="Screen Shot 2020-12-21 at 1 28 27 PM" src="https://user-images.githubusercontent.com/5395437/102809687-70b20a80-4390-11eb-92f5-7525c06958db.png">

I don't believe we've ever used default date values on `date` fields before, so this may be an existing bug that we just haven't seen until recently.  

_Note: If looks like if this is put behind some sort of conditional hide/show behavior, you can get the default values to populate correctly, but on normal form fields which are shown by default at load time, the default values are not populating._

If you need further clarification or examples, please speak to @alikemaltanriverdi

**Comment by timcortesi** [comment]
Removing the high priority flag from this, as we have a workaround that makes this no longer time critical.

**Comment by Cloverstone** [comment]
I can't replicate this - it seems to work fine to me - can you provide an example of this?

**Comment by timcortesi** [comment]
@alikemaltanriverdi Please reach out to @Cloverstone to show him an example of where / how this occurs.

**Comment by Cloverstone** [comment]
This is working as expected after initial load if the form is saved with an empty value that will override an "initial" value.
