### ISSUE TITLE
Workflows: Issue with Signature Box Styling in Pop-up Modal Windows

### ISSUE THREAD

**Issue by alikemaltanriverdi** [EscherLabs/Graphene#102]
**Description**
In Portal AWS Dev, the border of the signature box is overlapping with the action buttons of the form in a pop-up modal window triggered by an action in the workflow submission. This bug doesn't occur when the form is not submitted(in the origin state) if the signature is required. It only occurs in a submitted workflow where a modal window is popped up(with or without "Show Form" option is selected) after an action is taken.

**Feature / Subsystem**
This bug occurs in Graphene Workflows in Portal AWS Dev.

**To Reproduce**
1. Go to **actions** in any **state** in the **flow** of a workflow in portalawsdev.
2. Turn on "**Require Signature**" for the selected action.
3. Go to a workflow which has been submitted in portalawsdev, such as the one provided in "Link(s)"
4. Click on the action button, such as "Submit" button in the example submission
5. In the pop-up modal window, scroll down to the bottom of the form to see the signature box.
5. See the error in the styling of the "Signature Box". Additionally, please see the screenshot included below to have a better understanding of the styling issue.

**Link(s)**
1. Example workflow submission: http://portalawsdev.binghamton.edu/workflows/report/34442

**Additional context**
Please see the screenshot below to see the overlapping.

<img width="992" alt="Screen Shot 2020-12-21 at 4 12 57 PM" src="https://user-images.githubusercontent.com/11221504/102825041-03ac6e00-43ac-11eb-8673-19390daca0b9.png">

**This bug exists in the following browser(s)**
1. Chrome - Version 87.0.4280.88 (Official Build) (x86_64)
2. Safari - Version 14.0.1 (15610.2.11.51.10, 15610)

**Comment by Cloverstone** [comment]
It looks like this was a side effect of fixing the signature on phones. Is
it correct that it's not so much in modals but when it's in the footer of
the modal (with the action buttons)?

**Comment by alikemaltanriverdi** [comment]
- Yes, that is correct.
- Additionally, I just tested it on Safari on iPhone 12 Pro, and it looks good. Styling seems to be working fine for the smaller screens.

**Comment by timcortesi** [comment]
Assigning to @alikemaltanriverdi to test in http://portalawsdev.binghamton.edu

**Comment by alikemaltanriverdi** [comment]
- This looks good both for the pop-up window in an open submission. 
- It also looks good for an initial submission(a new submission/ submitting the form for the first time).

**Comment by timcortesi** [comment]
fixed in binghamton-prod branch as tested by @alikemaltanriverdi.  marking as closed.
