### ISSUE TITLE
Graphene Workflows: Option to Limit "user" field options by a specified group

### ISSUE THREAD

**Issue by timcortesi** [EscherLabs/Graphene#103]
It has been requested that the "user" type field within a Graphene Form have the option of limiting the population of allowable users by specifying a group.  

As it stands currently, all students / faculty / staff / applicants / etc are searchable via the "user" field.  With so many users in the system with common names, this can occasionally lead to confusion.  For relevant workflows, it may be useful to limit that population to only "staff" or "faculty", or even active "students".

See example below with similar names:
![image001](https://user-images.githubusercontent.com/5395437/103938740-babd1f00-50f8-11eb-8c38-c29afeeea86b.png)

**Comment by timcortesi** [comment]
I will work on modifying the search API to accept an optional group_id / group_slug as a limiter.

**Comment by timcortesi** [comment]
@timcortesi bumping this up

**Comment by timcortesi** [comment]
Back-End API is now implemented as per https://github.com/EscherLabs/Graphene/commit/e1c8b190b83bac523253bc0f6d4a9fd89ce81ce0

@alikemaltanriverdi, Please test as you are able
@Cloverstone I think this is ready to be implemented in the front-end

### How it works: 
This is what you could do before:
https://my.binghamton.edu/api/users/search/smith

But if you only want to search for “smith”s in ITS, you can now do this:
https://my.binghamton.edu/api/users/search/smith?groups=8

If you wanted to search for and “smith”s that are in the ITS group OR in the student groups, you can now also do this:
https://my.binghamton.edu/api/users/search/smith?groups=8,3

In the above example, note the comma between 8 and 3.  If you prefer standard html encoded format for arrays, you can do that as well
These are functionally identical:
https://my.binghamton.edu/api/users/search/smith?groups[]=8&groups[]=3
https://my.binghamton.edu/api/users/search/smith?groups=8,3

**Comment by timcortesi** [comment]
@Cloverstone -- A thought... 

It is possible that a person's group memberships may fluctuate, such that an individual who previously was a member of a group is no longer a member of that group.  

When you are loading the report page of a previously submitted workflow submission, it is probably correct to _not_ send the ?groups parameter, and simply look up the user based on the bnumber which is saved as part of that form's value.  ... I don't know if that breaks things, however.  (I feel like it would...)

My biggest concern is that someone will reopen an old workflow, and the data presented will not reflect the data as it existed when the workflow was originally submitted or processed.  (Which is bad)

**Comment by timcortesi** [comment]
Server-Side functionality has been added, but this is still pending implementation in the Form Builder (at least in binghamton-staging) as of the latest code release.

**Comment by alikemaltanriverdi** [comment]
@timcortesi @Cloverstone This has been live for a few months and working as expected.  Closing the issue.
