### ISSUE TITLE
Graphene: Main Page for a user who's only in a group (that doesn't have any app/workflow/ page instance) is broken

### ISSUE THREAD

**Issue by alikemaltanriverdi** [EscherLabs/Graphene#106]
**Description**
Main page of a user who is only in a group that doesn't have any app/ workflow/ page instances in it(such as **chegg**) is not loading properly. It seems like Graphene is trying to display a page with a content that doesn't exist.

**Feature / Subsystem**
Graphene

**To Reproduce**
Impersonate a user who is in a group that doesn't have any pages or apps or workflows instantiated in it, such as ** chegg**.
1. Go to the Users in admin dashboard
2. Search for a user that is in a group that doesn't have any apps or workflows or pages instantiated in it, such as the user (**ID: 38680**)
3. Click on Impersonate
4. You can see that the main page is not loading properly

**Console Errors**
<img width="1677" alt="Screen Shot 2021-01-19 at 8 30 44 PM" src="https://user-images.githubusercontent.com/11221504/105115492-e942de80-5a96-11eb-9267-ac1df99f5bae.png">

Source code of the page:
<img width="1023" alt="Screen Shot 2021-01-19 at 8 30 34 PM" src="https://user-images.githubusercontent.com/11221504/105115524-f52ea080-5a96-11eb-9758-2537476faeb7.png">

**Link(s)**
https://my.binghamton.edu/

**Additional context**
**Example User:** User ID: **38680**
Please see the screenshot of the main page(User's name is excluded):
<img width="1670" alt="Screen Shot 2021-01-19 at 5 06 07 PM" src="https://user-images.githubusercontent.com/11221504/105116340-936f3600-5a98-11eb-822b-2dab2e35f145.png">

Please contact me(@alikemaltanriverdi ) if additional information or documentation is needed.

**Comment by timcortesi** [comment]
Reassigning to @alikemaltanriverdi to test in http://portalawsdev.binghamton.edu/

**Comment by alikemaltanriverdi** [comment]
@timcortesi Tested a user that is not in any of the groups in Graphene. Confirmed, fixed.
