### ISSUE TITLE
Graphene Workflows: Sending 2 identical update emails to the owner after a logic block

### ISSUE THREAD

**Issue by alikemaltanriverdi** [EscherLabs/Graphene#107]
**Description**
Graphene workflow engine is sending 2 identical update emails to the owner of the submission after a logic block, if the actor and owner are same users(If the result of that logic routes it to a state where owner is a member of the assigned group.) This issue is probably caused because logic block's user is null and the function that is sending the email is not able to catch it.

**Feature / Subsystem**
Graphene workflows

**To Reproduce**
Steps to reproduce the behavior. 
1. Make sure the default emails are on for that instance.
2. Submit a new workflow that routes initial submission to a logic block.
3. Fill the form and click on submit.
4. See the emails.

**Console Errors**
None

**Link(s)**
Example Workflow Instance Id: 97

**Comment by alikemaltanriverdi** [comment]
Preparing a documentation for the emails that will explain which emails are being to who in which state

**Comment by timcortesi** [comment]
@alikemaltanriverdi -- do you know if this is still an issue after your changes to the WorkflowActionController?

Please indicate accordingly.

**Comment by alikemaltanriverdi** [comment]
This issue has been resolved with a major update on 7/6/2021. Please see the issue https://github.com/EscherLabs/Graphene/issues/134 for more information
