### ISSUE TITLE
Graphene: Debug information is shown to end users on a 404 page 

### ISSUE THREAD

**Issue by alikemaltanriverdi** [EscherLabs/Graphene#108]
**Description**
In Graphene, Debug information is shown to users on a 404 page even when user just an end user. The following error is appears on the screen:

>  phpCAS error: phpCAS::client(): ErrorException: session_start(): Cannot start session when headers already sent in /var/app/current/vendor/subfission/cas/src/Subfission/Cas/CasManager.php on line 97

**Feature / Subsystem**
Graphene

**To Reproduce**

1. Impersonate a user who is not an admin but just an end user.
2. Click on http://my.binghamton.edu/admin/apps/somejunk#scripts
3. See the error page with debug information

**Console Errors**
<img width="514" alt="Screen Shot 2021-01-22 at 1 27 22 PM" src="https://user-images.githubusercontent.com/11221504/105530299-95faa700-5cb5-11eb-9a0e-8a46c4e3bcb2.png">

**Link(s)**
Example link: http://my.binghamton.edu/admin/apps/somejunk#scripts

**Additional context**
Please see the screen shot:
<img width="1669" alt="Screen Shot 2021-01-22 at 11 31 56 AM" src="https://user-images.githubusercontent.com/11221504/105530728-2a650980-5cb6-11eb-8510-bb3b8cdd23a1.png">

**Comment by timcortesi** [comment]
@alikemaltanriverdi I am not able to replicate this issue following the instructions provided.  Can you please provide additional explanation for how this bug occurs?  It looks to me like this would be an issue specific to the CAS server behaving incorrectly, and not specifically a Graphene/Laravel bug.  Any help would be appreciated.

**Comment by timcortesi** [comment]
Unable to replicate this issue, so closing it.  If we find a way to reliably replicate this issue in the future, it will be reopened.
