### ISSUE TITLE
Error When Changing API Instance Version

### ISSUE THREAD

**Issue by nwallin1** [EscherLabs/Graphene#109]
**Description**
I select an API Instance and try to change the version. When I press save on the desired version, an error message appears and the modal where I selected the new version is still there. This makes is seem as though I didn't change the version properly, especially since the modal is still there. However, when I look at the information on the API Instance, the version has been changed. 

NOTE FROM TIM: "It's working fine but it's throwing an error when it goes to log the event"

**Feature / Subsystem**
Hermes DataProxy

**To Reproduce**
Steps to reproduce the behavior.  
(This should be as detailed as possible and should, if possible, reference an example where this behavior is easily reproducible and happens consistently.  Do not provide vague steps that are difficult to understand or yield inconsistent results)
1. Go to Hermes DataProxy
2. Click on 'API Instance'
3. Type 'veterans' in the name
3. Click on 'Veterans Certication Test'
4. Click the down arrow, next to the save button in the top right corner
5. Click 'Change Version'
6. Press 'Save', see error

**Console Errors**
From the developer console, please paste any _relevant_ errors you are experiencing.
![image](https://user-images.githubusercontent.com/32525511/105722566-ca5ba680-5ef3-11eb-8142-ade2f9a78fa9.png)

**Link(s)**
API Link:
https://my.binghamton.edu/admin/apiserver/hermesdp/api_instance/43

**Comment by timcortesi** [comment]
This was fixed in https://github.com/EscherLabs/GrapheneAPIGateway/commit/daa39829a88aa433485135953f9bca71af68d71c.  Marking as closed/complete
