### ISSUE TITLE
Graphene Forms: Adding "Strict" flag to form builder for Combobox type

### ISSUE THREAD

**Issue by alikemaltanriverdi** [EscherLabs/Graphene#110]
**Is your feature request related to a problem? Please describe.**
There is no option to set the **Strict** flag of the Combobox type fields in the form builder of Graphene. The only way to set it is to go into the script of the form and edit the script manually. Thus, most of the forms is not utilizing this capability, including workflows and microapps.

**Describe the solution you'd like**
The **Strict** flag is a critical attribute/ feature of the Combobox fields, so I believe that it should be added to the form builder so that all of the features/ capabilities of the Combobox fields can be used more effectively. It would also better to have all of the features of the Combobox fields in one place.

**Additional context**
Please contact @alikemaltanriverdi if more detailed documentation or explanation is needed.

**Comment by timcortesi** [comment]
@Cloverstone -- I asked @alikemaltanriverdi to submit this.  Please let me know if this seems reasonable.

**Comment by Cloverstone** [comment]
@timcortesi Yeah I had actually already added it as soon as he first asked
how to do it - it will be an easy task to check off

**Comment by timcortesi** [comment]
@Cloverstone ok -- can you please add to the binghamton-prod branch?

**Comment by Cloverstone** [comment]
Oh is this an immediate need?

**Comment by Cloverstone** [comment]
I added it - it didn't even have a high priority flag so I didn't think it
was an immediate need.

**Comment by timcortesi** [comment]
Marking as complete.  Closing
