### ISSUE TITLE
Duplicating Fields Issues with Graphene Forms

### ISSUE THREAD

**Issue by timcortesi** [EscherLabs/Graphene#113]
There are a number of issues when using duplicating fields within Graphene Forms.  A subset of these issues includes:

- You can often have 1 of a field, or 3 or more of a duplicated field, but attempts to submit a form with 2 of something often causes issues.
- Occasionally we get "null" fields instead of the expected value.
- I think we discussed addressing the ability to submit a form with "zero" values in a duplicatable field type.  I don't know if that's part of this.  

I believe @Cloverstone is working on a complete rewrite of the form duplication stuff to address many of these issues.

Please reach out to @alikemaltanriverdi with questions.

**Comment by alikemaltanriverdi** [comment]
@Cloverstone as far as I can see from my tests, this issue has been resolved. I believe that you can close this issue anytime you'd like. If I can any bugs with this behaviour, I can reopen this issue. Thank you.
