### ISSUE TITLE
GrapheneForms: Combobox Stops Listening for input after finding the matching string in the options in Firefox

### ISSUE THREAD

**Issue by alikemaltanriverdi** [EscherLabs/Graphene#119]
**Description**
Combobox is not acting as it is supposed in Firefox, it stops listening for input after it finds the matching string for the first time in **Firefox**. Please note that: this bug only happens in the Firefox for Comboboxes. User type and File Type fields are working as expected.

**Feature / Subsystem**
GrapheneForms

**To Reproduce**
1. Open a Firefox Browser and go to the example workflow: https://my.binghamton.edu/workflow/152/rf_boa_monthly_recon_new
2. Scroll down to the **Expense** section, start typing and select an option in the matching string
3. Choose any option in the dropdown, and select the combobox again and hit "Space" or any other button on the keyboard
4. Keep editing the string in the Combobox
5. See that it will not search for any string even it is empty or string length is bigger than 0

**Console Errors**
No errors

**Link(s)**
https://my.binghamton.edu/workflow/152/rf_boa_monthly_recon_new

**Test Environment**
Please see environments I used to test and replicate the issue.
1. **Firefox** Version: 88.0.1 (64-bit)
2. **Google Chrome** Version: 90.0.4430.212 (Official Build) (x86_64)
3. **MacOS** Version: 11.3.1
4. **Safari** Version: 14.1 (16611.1.21.161.6)

**Additional context**
<img width="1101" alt="Screen Shot 2021-05-18 at 9 29 31 AM" src="https://user-images.githubusercontent.com/11221504/118659815-a500ea00-b7bb-11eb-84d4-b9c1ad6029ba.png">
<img width="1077" alt="Screen Shot 2021-05-18 at 9 29 45 AM" src="https://user-images.githubusercontent.com/11221504/118659834-a8947100-b7bb-11eb-8470-635fa044ad0a.png">
<img width="1111" alt="Screen Shot 2021-05-18 at 9 30 02 AM" src="https://user-images.githubusercontent.com/11221504/118659845-ac27f800-b7bb-11eb-93e2-e6dbcc3b210d.png">

Please let me know if you need additional documentation or any example test cases.

**Comment by Cloverstone** [comment]
looks like I asked for status confirmation  on this over a year ago - @alikemaltanriverdi  can you take a look

**Comment by Cloverstone** [comment]
I apologize that I seemed to be blaming you in any way, I certainly didn't mean to.  I was simply stating that I stated that a year ago and didn't remember anything more about it or why I even asked for confirmation.  Thank you for confirming this is resolved, I will close it out.
