### ISSUE TITLE
Workflow errors - Clarify

### ISSUE THREAD

**Issue by Cloverstone** [EscherLabs/Graphene#127]
Display a summary of errors. Focus on first error on submit. Navigate on clicking error to field with error. Make sure hidden errors not triggering invalid form.

**Comment by alikemaltanriverdi** [comment]
@Cloverstone I believe this issue has been addressed with the current version of Graphene that is currently in portalAWSDev. During my tests, I was able to confirm that this issue has been resolved. You can close this anytime you'd like.
