### ISSUE TITLE
GrapheneAPIGateway: Add Form-based Options to API/API Instance

### ISSUE THREAD

**Issue by timcortesi** [EscherLabs/Graphene#130]
Currently, whenever we want to configure / customize an API Instance, we are required to set up custom resources, and then map those back to an API.  While that is correct in some situations (example: databases), it is not really correct for certain API Specific controls (turning functions on / off, storing simple configuration strings, etc).  In those situations, we are arguably abusing the "resources" function, which has led to dozens of single-use resources that only have application with a very specific API (which was not the original intention).

Rather, it should be possible to have a simple "options" form, which is defined as part of the API.  This should be nearly identical to the "options" form which is configured for MicroApps.  

From within the API editor, I expect that there would be a new tab called "Options", which provides access to the GrapheneForm Builder, and generates a new "options" form.  

From the API Instance viewer, I expect that there would be a new tab called "Options", where an admin can configure the various options which are available.  

These options should then be available via an $options variable, which is accessible from within the API Code.  (In addition to the existing $args, and $resources variables).  

Note that this will require some modifications to the database for managing and storing these additional data fields.

**Comment by timcortesi** [comment]
The APIGateway part of this code has been written, and is committed here: https://github.com/EscherLabs/GrapheneAPIGateway/commit/f5379ae9906e4e70ac220cf1739c4335b9f15a93

The UI for building the default api options form, and configuring instance level options still needs to be created.

**Comment by Cloverstone** [comment]
api gateway has some more changes that will need to be pushed as well
