### ISSUE TITLE
Outstanding Issues with bingahmton-staging 6/22/21

### ISSUE THREAD

**Issue by timcortesi** [EscherLabs/Graphene#134]
This single issue will track any outstanding issues w/ the current binghamton-staging branch, as deployed in [portalawsdev.binghamton.edu](http://portalawsdev.binghamton.edu)

Please Edit this Issue Description, and add any issues discovered in the list below.

  - [x] Download button in default template for an empty Base64 field is downloading the HTML source of the page. I believe the download button should be hidden (or disabled?) if there is no document uploaded for Base64 type fields. http://portalawsdev.binghamton.edu/workflows/report/70048 <br>**Example Report:** <img width="1093" alt="Screen Shot 2021-06-29 at 11 46 15 AM" src="https://user-images.githubusercontent.com/11221504/123828572-a00d7b00-d8cf-11eb-8557-f0ad7a0754c5.png"><br>**Downloaded file:**<img width="1188" alt="Screen Shot 2021-06-29 at 11 42 45 AM" src="https://user-images.githubusercontent.com/11221504/123828117-32614f00-d8cf-11eb-841a-21ab61206481.png">
  - [x] When the last line of a method is commented out in workflows, it affects the report of the workflow submission: http://portalawsdev.binghamton.edu/admin/workflows/65#methods . **Example submission**:http://portalawsdev.binghamton.edu/workflows/report/70034. Please see the console error: <img width="771" alt="Screen Shot 2021-06-23 at 9 20 43 AM" src="https://user-images.githubusercontent.com/11221504/123104146-b2397600-d404-11eb-8819-12db3cada52e.png">
     - Please note that: this issue also exists in the production
     - @Cloverstone I am still seeing this issue in http://portalawsdev.binghamton.edu/workflows/report/70033 (http://portalawsdev.binghamton.edu/admin/workflows/65#methods). Has the fix been deployed?
  - [x] @Cloverstone When managing MicroApp Instance and Workflow Instance resources, there used to be a "None" option, where mapping a resource to an endpoint was not required.  (We use this in cases where the resource does not require authentication, and the full URL is provided in the resource itself.)  The "None" option does not exist for MicroApp Instances and Workflow Instances in the binghamton-staging branch.  
<img width="761" alt="Screen Shot 2021-06-29 at 9 37 26 AM" src="https://user-images.githubusercontent.com/5395437/123807196-a561ca00-d8bd-11eb-98bf-df872b6c1ae9.png">
In cases where "None" is selected as an endpoint, instead of the endpoint_id, the value should be set to "none".

  - [x] Time format is not user readable in Workflow Assignments: http://portalawsdev.binghamton.edu/workflows/assignments 
     - Fixed: https://github.com/EscherLabs/Graphene/commit/e1d4bf785ec259ba092fb34d7eb6d5dbef4eb3c3

  - [x] Issues with Form Builder Validation: #136 (New Issue) **Marking as completed, though this will need to be addressed in a separate issue.**

  - [x] There is a new error in the workflow forms and microapp forms (Probably in gforms?) http://portalawsdev.binghamton.edu/admin/workflows/5#forms - http://portalawsdev.binghamton.edu/admin/apps/429#forms. When you first go to the workflow, you will be seeing the following error: <img width="866" alt="Screen Shot 2021-06-28 at 4 14 54 PM" src="https://user-images.githubusercontent.com/11221504/123698895-a0a10580-d82c-11eb-84a9-c08bf6933635.png"> If you ignore it and add a new field( any type), then the error below is logged to the console: <img width="602" alt="Screen Shot 2021-06-28 at 4 18 50 PM" src="https://user-images.githubusercontent.com/11221504/123698986-bca4a700-d82c-11eb-9775-0f0ebdf88d4d.png">.<br>Once you save the workflow and refresh the page, you will be seeing that none of the changes made were saved.
@alikemaltanriverdi  This was an error on every page within the Admin and was corrected by: https://github.com/EscherLabs/Graphene/commit/9cdcb48e8b6d275a617722e1bf2a39e351b5d7b6
The Berry Datepicker stuff has been manually re-added to the Binghamton theme.

  - [x] Base64 type fields is not being purged on "Purge All Files" tasks. Since it is being treat as a regular field, this might be an expected behaviour, but I wanted to point this out. http://portalawsdev.binghamton.edu/admin/workflows/67#flowchart 
  Example Submission: http://portalawsdev.binghamton.edu/workflows/report/70044
@alikemaltanriverdi This is expected, as base64 type file uploads are not considered workflow file uploads.  If you need to delete a file of this type, you would need to use "Purge Fields By Name" instead.   In general, I would recommend against using base64 upload types with workflows, unless there is a specific use case for doing so.  That form type is generally intended for MicroApps where file uploads are required, and there is no standard mechanism for storing them.  (Workflows already has a way to handle file uploads)
@timcortesi Thank you for the information. I'll keep this in mind for the future workflows and microapps.
 - [x] Duplicate "Update" emails after a logic block. Since the actor of a logic block is not a user, line 565 in WorkflowSubmissionActionController will return **true** even if the actor is the owner. 
Fixed with https://github.com/EscherLabs/Graphene/commit/f0aa3bbce4d1bb67fc9c70778e6a70b93905690e
  - [x] Not sure if this an expected behaviour, but a group can be its own composite. **<TJC @alikemaltanriverdi This is intentional, and is used in cases where you want to limit visibility to just the group members, and not any of the other composite groups.>**  It can also be added multiple times. **<TJC -- @alikemaltanriverdi This is not accurate, as there exists a uniqueness constraint on that table `$table->unique(['group_id','composite_group_id']);`.  Refresh the page, and you will see that the composite does not exist more than once. >** I just wanted to point this out: http://portalawsdev.binghamton.edu/admin/groups/321/composites <img width="810" alt="Screen Shot 2021-06-25 at 2 42 39 PM" src="https://user-images.githubusercontent.com/11221504/123471497-dd1df880-d5c3-11eb-8e01-efb34187eb3a.png">
    - Please note that: This behavior also exists in myBinghamton(PROD).
 - [x] Admin (+New) Button is not working in the following ways.... **Recommend hiding this button for this release**
     - Creating a new App Instance, Workflow instance, Page, Endpoint, Image and Link in an app /workflow is not working. To replicate this issue, please go to http://portalawsdev.binghamton.edu/admin/apps/430, click on **+New** icon on the top left side of the screen, select one of the items mentioned above. Console error: <img width="1107" alt="Screen Shot 2021-06-23 at 9 45 37 AM" src="https://user-images.githubusercontent.com/11221504/123108012-0a25ac00-d408-11eb-867c-48a0b4360566.png"> <img width="919" alt="Screen Shot 2021-06-23 at 9 48 04 AM" src="https://user-images.githubusercontent.com/11221504/123108114-21fd3000-d408-11eb-8100-5275cfad0a0e.png">
     - Lead Developer dropdown options are not populated when creating a new App or Workflow in an app /workflow is not working. To replicate this issue, please go to http://portalawsdev.binghamton.edu/admin/apps/430, click on **+New** icon on the top left side of the screen, select App or Workflow. See that there can be no Lead Developer chosen for that app/ workflow: http://portalawsdev.binghamton.edu/admin/apps/430
 - [x] Only the names are shown for the base64 type files on the default workflow report template. Since those file are not included into the all files, users can only see the file name instead of its content. It's also not possible to download base64 type file or use the file baseURI as a source in img tag.
 - [x] Validations in App and Workflow Instances are not running when required fields are empty: http://portalawsdev.binghamton.edu/admin/appinstances/581 - http://portalawsdev.binghamton.edu/admin/workflowinstances/108
 - [x] The value of the "icon" which we store in the database is expected to be just "heart" or "circle" or whatever.  It looks like you're setting them as "fa fa-heart" or "fa fa-circle".  This is causing issues in blade when the icons are rendered, and in other places where we use png based icons "heart.png" or "circle.png".  This is true for all places where we use icons including pages, app instances, and workflow instances.
 - [x] Can't edit Workflow Instances or App Instances with (Latest Working or Published) Version from http://portalawsdev.binghamton.edu/admin/groups/256/workflowinstances or http://portalawsdev.binghamton.edu/admin/groups/60/appinstances as it returns the following SQL Error:
```
message: "SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'workflow_version_id' at row 1 (SQL: update `workflow_instances` set `workflow_version_id` = , `icon` = fa fa-heart, `groups` = [], `workflow_instances`.`updated_at` = 2021-06-23 08:13:08 where `id` = 79)"
```
  - @Cloverstone I'm pretty sure you already fixed this, not sure why this is showing up again
  - [x] Filtering on Data grid fields has been moved to its own issue...#135
  - [x] In http://portalawsdev.binghamton.edu/admin/workflows/65#flowchart, "Last_State" state is being seen as a logic block and it's throwing a console error when I click on it: <img width="653" alt="Screen Shot 2021-06-22 at 4 50 36 PM" src="https://user-images.githubusercontent.com/11221504/122997478-0a776600-d37a-11eb-97f7-726a66784fbd.png">
    - To replicate this issue, create a new state with spaces in its name (Final State), after the creation make that state "Closed", it replaces the name with underscores(Final_State). Once this happens save the workflow and try to click on that state, you will see the console error.
 - [x] There is a "debugger" left in the code in lib.js and it runs when the dev console is open in a workflow http://portalawsdev.binghamton.edu/admin/workflows/65#forms : <img width="669" alt="Screen Shot 2021-06-22 at 4 52 19 PM" src="https://user-images.githubusercontent.com/11221504/122998070-97baba80-d37a-11eb-9b8f-baed3e0316c8.png">
 - [x] Workflow submissions are not loading in http://portalawsdev.binghamton.edu/workflows and http://portalawsdev.binghamton.edu/workflows/history -> See the server Error: <img width="718" alt="Screen Shot 2021-06-22 at 11 24 51 AM" src="https://user-images.githubusercontent.com/11221504/122953126-7b078e00-d34c-11eb-9ca0-58bacfbc290d.png">
   - unable to replicate is this possibly related to your (@alikemaltanriverdi) account like we saw previously?
   - @Cloverstone This issue is valid for my account and Tim's account, this might also affect other users. I'm still testing.
   - it looks like you might get that error if you have a submission that currently has no assignee
 - [x] Templates are not being added to the Body Template for the Task(Custom) Emails as soon as they're added. Page refresh is needed. http://portalawsdev.binghamton.edu/admin/workflows/65#flowchart
 - [x] When creating a new action for a state in the flow of a workflow, the focus is lost as soon as the first letter is entered in the "Label" of the action. You need to reselect the "Label" field to keep typing the name. http://portalawsdev.binghamton.edu/admin/workflows/65#flowchart 
 - [x] It seems like "Title" field **in Config/ Datamap** is intended to change the name of the workflow( maybe instance name?) for the end user, but I seem to fail to see the name given in that "title
    - no, this was added to generate titles of individual submissions based on form data - until multiple un-submitted workflows are allowed this field is not used
 - [x] In workflow reports, SignaturePad is not being rendered on the modal as expected where a signature is required. And signature validation is not being enforced. Example: http://portalawsdev.binghamton.edu/workflows/report/70017. See the console error: <img width="642" alt="Screen Shot 2021-06-22 at 11 40 59 AM" src="https://user-images.githubusercontent.com/11221504/122956242-d2a6f900-d34e-11eb-88f4-1251172df1c5.png">
- [x] Currency Type field format is not being shown as expected in the default workflow report template: http://portalawsdev.binghamton.edu/workflows/report/70016
- [x] In workflow reports, "Download All" button is disabled even though file management is turned on for the given state: http://portalawsdev.binghamton.edu/workflows/report/70029
- [x] [@timcortesi working on this] In the admin view, Lead Developer is not being filtered correctly in the datagrid for MicroApps: http://portalawsdev.binghamton.edu/admin/apps 
- [x] [@timcortesi working on this] In the admin view, Lead Developer is not being populated correctly in the **Edit** modal for MicroApps and Workflows: http://portalawsdev.binghamton.edu/admin/apps - http://portalawsdev.binghamton.edu/admin/workflows
- [x] Workflow Form builder is not pre populating/ drawing the existing form: http://portalawsdev.binghamton.edu/admin/workflows/5
- [x] Issue: Server Error -> Failing to send default emails to the assigned groups (http://portalawsdev.binghamton.edu/admin/workflows/65), see the server error: <img width="795" alt="Screen Shot 2021-06-22 at 10 58 40 AM" src="https://user-images.githubusercontent.com/11221504/122950651-9ffb0180-d34a-11eb-810c-2880676594b3.png"> 
- [x] Emails are using the subject as email body. See the line 679 in WorkflowSubmissionActionController.php
- [x] When chrome developer console is open in a workflow, console throws an error and Chrome pauses the operations when another tab is selected. e.g. Change the tab from "**Form**" to "**Flow**". (http://portalawsdev.binghamton.edu/admin/workflows/65) See the console error and source: <img width="1065" alt="Screen Shot 2021-06-22 at 11 47 06 AM" src="https://user-images.githubusercontent.com/11221504/122957256-c3747b00-d34f-11eb-8259-8c099c80bff2.png"><img width="904" alt="Screen Shot 2021-06-22 at 11 49 01 AM" src="https://user-images.githubusercontent.com/11221504/122957365-de46ef80-d34f-11eb-860b-2a2e1f3f48d2.png"> 
    - @alikemaltanriverdi unable to replicate given that workflow and those instructions, there must be some other condition
- [x] In Workflow instances in groups, Version, Raw Data, Report buttons (http://portalawsdev.binghamton.edu/admin/groups/153/workflowinstances), and Version button in App instances (http://portalawsdev.binghamton.edu/admin/groups/153/appinstances) are not tied to a model (I'm guessing that "action_name" is used instead of "model:action_name"). There is also a "debugger" left in lib.js that runs on "Edit" action for Workflow Instances and App Instances.
    - Also "Sort" button in app instances (http://portalawsdev.binghamton.edu/admin/groups/153/appinstances) is not tied to any model (I'm guessing?). It's not doing anything on click.
    - You may need to refresh - all of these seem to be working for me but I did need a shift+refresh  first

**Comment by timcortesi** [comment]
@alikemaltanriverdi  - 

@Cloverstone and I feel that all of these issues have either been fixed or spawned off into their own issues (where they will be fixed outside of this issue).  Can you please retest all issues outlined here and verify that everything is now working as expected?

**Comment by alikemaltanriverdi** [comment]
Sure, I'm on it.

**Comment by timcortesi** [comment]
Pushed an major update to myBinghamton which reflects all of these issues on 7/6/21.  Closing this issue.
