### ISSUE TITLE
GrapheneAPIGateway: Using / in the request parameters causes bugs

### ISSUE THREAD

**Issue by alikemaltanriverdi** [EscherLabs/Graphene#140]
**Description**
When making a request in GrapheneAPIGateway, using **/** in a request parameter value causes bugs

**Feature / Subsystem**
APIGateway

**To Reproduce**
1.  In a test api, send test/pdf as a request parameter value (it can also be a post request)
2. See the error returned from API: 
   ```json
    {
    "error": "API call does not exist"
    }

**Console Errors**
N/A

**Link(s)**
Since there is currently no test APIs, I am not able to share the real links. Please contact me (@alikemaltanriverdi ) for additional information, such as parameters.

**Comment by alikemaltanriverdi** [comment]
@timcortesi There's  a **"{\n____\"comment\":\"Wanted_to_remind_you\"\n}": ""** comment was left in the $args array in **GrapheneApiGateway**, and it will probably break some up the APIs that use Laravel Query Builder's update() function as follows: update($args)

**Comment by timcortesi** [comment]
This should now be fixed.  @alikemaltanriverdi please test and close this issue if found to be working correctly.

**Comment by timcortesi** [comment]
See Screenshot:

<img width="515" alt="Screen Shot 2021-07-14 at 5 04 06 PM" src="https://user-images.githubusercontent.com/5395437/125692718-9d527197-f832-4c77-8176-d4693cc37f65.png">

**Comment by alikemaltanriverdi** [comment]
@timcortesi It looks like it's as expected working on my side as well. I think you can close this issue

**Comment by timcortesi** [comment]
Closing based on testing by @alikemaltanriverdi above.
