### ISSUE TITLE
Graphene Forms: base64_file Type Field Issues

### ISSUE THREAD

**Issue by alikemaltanriverdi** [EscherLabs/Graphene#141]
**Description**
1- When a .txt or .csv type file is uploaded into the **base64_file** type field, **dataURI** attribute of the field is returning the content of the file instead of base64 encoded string
2- When a **.pages**, **.numbers**, **.key** (all Apple OS -iOS, OSX, etc. - document types) type file is uploaded into the **base64_file** type field, **type** attribute of the field is returning empty string

**Feature / Subsystem**
Graphene Forms

**To Reproduce**
Steps to reproduce the behavior.  
1. https://my.binghamton.edu/app/322/documents_management
2. Click on any case in the datagrid, which will take you to the related case tab
3. Scroll down to "Uploaded Files" section
4. Click on **+Add New File** button to open the document upload modal
5. Open the developer console
6. Upload .txt, .csv, .numbers, .pages, .key, etc. (mentioned above) 
7. Click on "Upload"
8. Debugger will stop the execution of the app, then go to the "Console" tab of your developer console
9. Type **e.form.get().file** to get the base64_file type field's attributes
10. See dataURI attribute (for .txt, .csv) or type (for Apple document types) attribute depending on the document uploaded

**Console Errors**
N/A

**Link(s)**
1- DEV Instance: https://my.binghamton.edu/app/322/documents_management#collapsesection1
2- Microapp: https://my.binghamton.edu/admin/apps/438#scripts (Debugger is placed at line: 91)

**Additional context**
If more documentation or examples are needed, please contact to @alikemaltanriverdi

**Comment by Cloverstone** [comment]
At the very least the setup for this seems to have changed - I am having a little trouble replicating some of this - @alikemaltanriverdi  could you just take a minute and confirm the issue is still there and update the relevant  information (line of error etc.)  - thanks

**Comment by alikemaltanriverdi** [comment]
@Cloverstone It seems like this issue has been fixed in the production (myBinghamton), so I'm closing the issue.
