### ISSUE TITLE
Graphene: Increasing description column char limit in the apps and workflows tables in database

### ISSUE THREAD

**Issue by alikemaltanriverdi** [EscherLabs/Graphene#174]
**Is your feature request related to a problem? Please describe.**
As the latest changes and requirements showed to us, having 255 chars as **description** column of the workflows table and the apps table is not enough. 

**Describe the solution you'd like**
Can you please increase the column size for the description **column** in the **workflows** table and the **apps** table in database to 500 chars or 1000 chars as you see fit?

**Additional context**
When increasing the size of the columns of the database tables, can you also place length limits to the related forms fields (description, and maybe other fields?), such as New/ Edit action action form of http://portalawsdev.binghamton.edu/admin/workflows
or 
New/ Edit action method form of http://portalawsdev.binghamton.edu/admin/apps

**Comment by alikemaltanriverdi** [comment]
Sounds good, thank you

**Comment by Cloverstone** [comment]
This is now closed - requires an update from composer and a migration
