### ISSUE TITLE
Graphene: EHS PI Portal is not Working as expected

### ISSUE THREAD

**Issue by alikemaltanriverdi** [EscherLabs/Graphene#178]
**Description**
EHS PI Portal Microapp is not working as expected.

**Feature / Subsystem**
Graphene

**To Reproduce**
Steps to reproduce the behavior.  

1. Go to users, and impersonate me
2. Go to http://portalawsdev.binghamton.edu/app/122/ehs_pi_portal
3. Click on Manage Labs/ Spaces dropdown and select a lab/ space
4. See error in the developer console.

**Console Errors**
<img width="668" alt="Screen Shot 2022-01-14 at 3 48 08 PM" src="https://user-images.githubusercontent.com/11221504/149583104-6ed51e08-bcd9-4bcc-8072-7c3df33f558a.png">

**Link(s)**
http://portalawsdev.binghamton.edu/app/122/ehs_pi_portal

**Additional context**
@Cloverstone let me know if you need additional documentation.

**Comment by Cloverstone** [comment]
this is a bug in the app and exists in production as well
