### ISSUE TITLE
Graphene: Faculty Promotion and Tenure App is not working as expected

### ISSUE THREAD

**Issue by alikemaltanriverdi** [EscherLabs/Graphene#182]
**Description**
An error is thrown to the developer console in the app, and it doesn't let you to edit the case info.

**Feature / Subsystem**
Graphene

**To Reproduce**
Steps to reproduce the behavior.  
1. Go to http://portalawsdev.binghamton.edu/app/ali_kemal_test_group/faculty_promotion_and_tenure_doc_dev
2. Open the developer console
3. See error
4. Then Click on a case to go to the case page
5. Once you're in the case page, click on "Edit This Info" button to see the same error thrown into the developer console.

**Console Errors**
<img width="629" alt="Screen Shot 2022-01-18 at 10 01 23 AM" src="https://user-images.githubusercontent.com/11221504/149962235-c696230e-082d-40d0-b94c-bce9528cc173.png">

**Link(s)**
http://portalawsdev.binghamton.edu/app/ali_kemal_test_group/faculty_promotion_and_tenure_doc_dev

**Additional context**
@Cloverstone Let me know if you need any additional documentation.

**Comment by alikemaltanriverdi** [comment]
@Cloverstone It seems like the fix has caused to another bug, please see the error below:

<img width="629" alt="Screen Shot 2022-01-18 at 10 01 23 AM" src="https://user-images.githubusercontent.com/11221504/150000896-a6d434de-fa1b-4c65-a08f-d5f8d2af2f18.png">

To reproduce: 

1. Go to the link: http://portalawsdev.binghamton.edu/app/ali_kemal_test_group/faculty_promotion_and_tenure_doc_dev
2. Click case 81 row
3. In the case page, click on "Edit this information"
4. See the bug in the developer console

**Comment by Cloverstone** [comment]
i am not seeing this error,  can you confirm that you have fully refreshed?

**Comment by Cloverstone** [comment]
i was able to replicate - this is a completely different issue actually - see issue #183

**Comment by alikemaltanriverdi** [comment]
@Cloverstone Yes, I can confirm that I completely refreshed it. I'm sorry that I put the wrong case number for this, and the issue is there for the case 71.
