### ISSUE TITLE
WYSIWYG Content Widget Odd Behavior on myBinghamton Home Page (Only)

### ISSUE THREAD

**Issue by timcortesi** [EscherLabs/Graphene#184]
1. Visit the myBinghamton home page: http://portalawsdev.binghamton.edu/page/main/mydashboard
2. Add a WYSIWYG widget type
3. Note that the summernote editor does not appear:

<img width="694" alt="Screen Shot 2022-01-18 at 10 01 03 AM" src="https://user-images.githubusercontent.com/5395437/149962258-56d80423-9925-4649-8f20-e23953e91cec.png">

Notably, this appears to ONLY happen on the home page of myBinghamton, and is working correctly on other pages.  

Per @Cloverstone:
> Its a problem when adding it, it appears - one of the apps seems to be
> overriding (or breaking) the options behavior so the type is set to an
> empty string which then defaults to a text field. Will likely need to go
> through and try adding one after removing each app on the page one at a
> time to identify

**Comment by Cloverstone** [comment]
This doesn't appear to be the case anymore. Closing since it cant be replicated - possible that a fix was pushed already.
