### ISSUE TITLE
API Gateway: The first resource of the instance of an API is not being set correctly

### ISSUE THREAD

**Issue by alikemaltanriverdi** [EscherLabs/Graphene#195]
**Description**
Everytime you visit an API instance, the first resource is set to the first item in the dropdown list, even though you do not visit "Resources" tab, and it is causing the change of the resource when saving the instance, whether a production instance or a dev instance. This issue might be related to "duplicated" fields in the forms.

**Feature / Subsystem**
API Gateway

**To Reproduce**
Steps to reproduce the behavior.  
1. Go to an API instance in the Graphene API Gateway
2. Click on Resources, and see that the first resource is set to the first item in the resources dropdown
3. Compare the resource that is set in the "resources" tab with response from the server, and you'll see that it's wrong.
4. If you save the instance, you'll also see that it's saving the instance with the wrong resource

**Console Errors**
None

**Link(s)**
Since I do not think it is a good idea to use API Gateway link here, I will not be providing link in this issue. Please contact me for the link

**Additional context**
@Cloverstone I'll send you link in the private messaging, and let me know if you need any additional documentation.

**Comment by alikemaltanriverdi** [comment]
@Cloverstone I have cleared my cache, but the issue is still happening as it was before.

**Comment by Cloverstone** [comment]
looks like code was committed but not deployed - please try again

**Comment by alikemaltanriverdi** [comment]
Confirmed, fixed.
