### ISSUE TITLE
Graphene Workflows: Creating options type without adding options is causing workflow to crash after saving

### ISSUE THREAD

**Issue by cankaturkmen** [EscherLabs/Graphene#198]
**Description**
In Workflow Forms, when an options field is created, saving without adding the options throws the error.

**Feature / Subsystem**
Workflows

**To Reproduce**

1. Create a new workflow
2. Click Form Section
3. Create an options field without adding the options
4. Save & Refresh the page
5. See the error

**Console Errors**
_Uncaught TypeError: Cannot read properties of null (reading 'type')_

**Link(s)**
https://my.binghamton.edu/admin/workflows/82

**Additional context**
  Creating Options Field|  Leave Options Empty
:-------------------------:|:-------------------------:
 <img src="https://user-images.githubusercontent.com/90630568/153666661-7c61c8f1-2b94-4706-86be-2a0c1c61046a.png" width="1000" height="300">  | <img src="https://user-images.githubusercontent.com/90630568/153666667-9a1af750-cc62-4a1f-b6ac-02109045c82f.png" width="200" height="300"> 

 Save & Refresh | Console Error
:-------------------------:|:-------------------------:
<img src="https://user-images.githubusercontent.com/90630568/153666674-09c83f41-efd2-4390-a219-0e2ca05390fd.png" width="400" height="300"> | <img src="https://user-images.githubusercontent.com/90630568/153666680-da5451e8-4618-44c4-94fa-328c5242b8eb.png" width="300" height="100">

**Comment by alikemaltanriverdi** [comment]
@Cloverstone I just tested this for the Microapp, and I can confirm that this bug only affects workflows.

**Comment by timcortesi** [comment]
Assigning to @cankaturkmen to test in http://portalawsdev.binghamton.edu/
