### ISSUE TITLE
Expanded User Object Stored in Workflow Data for Graphene Workflows

### ISSUE THREAD

**Issue by timcortesi** [EscherLabs/Graphene#201]
NOTE: We cannot reliably replicate this issue.. investigating further...

It seems like this is somehow related to https://github.com/EscherLabs/Graphene/issues/203 but not in a way that I can reliably identify.

If you include a "user" type object within a form, the graphene unique_id (bnumber) of the user should be stored in the workflow data object.  That is happening correctly.  For example, A form might have the following data.  (The below example is the expected behavior)

```json
{
    "supervisor":"B00505893"
}
```

However, for some reason, an expanded copy of the user object (appended with "-user") is also being stored in the workflow data object, so the actual object looks like this:

```json
{
    "supervisor":"B00505893",
    "supervisor-user": {
        "email": "tcortesi@binghamton.edu",
        "params": {
            "bnum": "B00505893",
            "pidm": "520689",
            "pods": "tcortesi"
        },
        "last_name": "Cortesi",
        "unique_id": "B00505893",
        "first_name": "Tim"
    }
}
```

This is not inherently problematic, but it is not consistent with the expected or prior behavior of the workflow functionality.

**Comment by alikemaltanriverdi** [comment]
@Cloverstone I was able to replicate this issue:

1. Go to a workflow
2. Create a section
3. Put a User field in that section
4. Set "Show" condition to _flowstate = origin for the user field
5. Go to workflow and submit, you can see that test_user-user object is included in the history.data.test (the path to the object) object
6. See http://portalawsdev.binghamton.edu/workflows/report/94195

**Comment by alikemaltanriverdi** [comment]
@Cloverstone confirmed, fixed
