### ISSUE TITLE
Workflow does save field value if there exists a Value Calculation (method) on a "user" type field

### ISSUE THREAD

**Issue by timcortesi** [EscherLabs/Graphene#203]
Note: I think we only use this feature (Value Calculations on User type fields) in one workflow (Telecommuting Application), so I do not believe that this is a widespread issue.  However, any telecommuting application which was submitted after we pushed the update to the portal appears to be broken.

It seems like https://github.com/EscherLabs/Graphene/issues/201 might be in some way related to this, but I'm not clear how.

If you have a "user" type field, which is populated using a method (Value Calculation).  For example:

Form Object:
```json
{
	"fields": [
		{
			"name": "test",
			"type": "user",
			"label": "Test",
			"method": "method_1"
		}
	]
}
```

Method 1:
```javascript
return "B00450942";
```

When you first go to populate the form, everything looks right, and the BNumber 'B00450942' is correctly populated as "Ali Kemal Tanriverdi".  

<img width="927" alt="Screen Shot 2022-03-02 at 4 33 28 PM" src="https://user-images.githubusercontent.com/5395437/156453303-12479a7e-9983-40e8-8877-66ea7d8f057c.png">

HOWEVER...

When you submit the workflow, the data which is stored in the database is an empty string:

```json
{
	"test": ""
}
```
Value calculations / methods appear to work correctly for non user type fields.  But user type fields are not saved/stored if there exists a value calculation / method attached to it.

**Comment by alikemaltanriverdi** [comment]
- @Cloverstone I can still see that a supervisor-user attribute is being added to the asign_to object.
Please see the **assign_to** object of the **data** in history in http://portalawsdev.binghamton.edu/workflows/report/75639

- If a user field is being set by a method, it still only shows the BNumber of the user in the user field.
- See the submission action history (see of the earlier actions in the history section that is located on the left hand side of the workflow report).

**Comment by Cloverstone** [comment]
Thats not what this issue is about is it? I believe that was a different issue. The issue opened here i believe has been addressed.

**Comment by Cloverstone** [comment]
I believe issue #201 is the one you are referring to.

**Comment by alikemaltanriverdi** [comment]
@Cloverstone I was also be able to replicate the issue. Please see the steps to replicate:

1. Go to a workflow (http://portalawsdev.binghamton.edu/admin/workflows/83)
2. Create a user field and set its show condition to _flowstate = origin, parse = true, report = true
3. Create a method that returns "B00450942"
4. Set "value calculation" of the user field to this method
5.  Save
6. Go to the workflow http://portalawsdev.binghamton.edu/workflow/153/test_for_user_fields and submit your form
7. Go to your submission, and see the history.data object. See that the value of the user field is still there
8. Click on Submit button in newstate0
9. Once the submissions is in the new state, check history.data object
10.  See that value is gone

**Comment by Cloverstone** [comment]
This is a different issue and the original issue is fixed - closing this one and opening as new.
