### ISSUE TITLE
MicroApps / Workflows: It is now not possible to set a 'versioned' workflow / app to 'Latest Working or Published'

### ISSUE THREAD

**Issue by timcortesi** [EscherLabs/Graphene#204]
Note: This bug was working correctly in the following commit.  This bug was introduced AFTER this commit: https://github.com/EscherLabs/Graphene/commit/7fdbcd1d2e6f575654b9252b46b34153ff973941

It was introduced in: https://github.com/EscherLabs/Graphene/commit/0f722cfc868699809197b5c6f44c97e3e7df24d6 OR https://github.com/EscherLabs/Graphene/commit/ab3e8ea7f275e03faf2dc57f480458063ca33ed7

For any/all workflows and micro app instances that are locked to a particular version, it is no longer possible to change the version back to "Latest Working / Published" (NULL in the database).

I don't think this issue has anything to do with versioning itself, but that the issue seems to be manifesting itself in regards to versioning.

**Comment by Cloverstone** [comment]
it was ab3e8ea - looking into fix, noting for reference

**Comment by timcortesi** [comment]
Reassigning to @alikemaltanriverdi to test in http://portalawsdev.binghamton.edu/

**Comment by alikemaltanriverdi** [comment]
@Cloverstone changing the version to "Latest (Working/ Published)" working for the Microapp instances, but it is **NOT** working for workflow instances.

**Comment by alikemaltanriverdi** [comment]
@Cloverstone confirmed, fixed.
