### ISSUE TITLE
Update of hidden combobox value from function in strict mode not saving

### ISSUE THREAD

**Issue by Cloverstone** [EscherLabs/Graphene#205]
@Cloverstone I was also be able to replicate the issue. Please see the steps to replicate:

1. Go to a workflow (http://portalawsdev.binghamton.edu/admin/workflows/83)
2. Create a user field and set its show condition to _flowstate = origin, parse = true, report = true
3. Create a method that returns "B00450942"
4. Set "value calculation" of the user field to this method
5.  Save
6. Go to the workflow http://portalawsdev.binghamton.edu/workflow/153/test_for_user_fields and submit your form
7. Go to your submission, and see the history.data object. See that the value of the user field is still there
8. Click on Submit button in newstate0
9. Once the submissions is in the new state, check history.data object
10.  See that value is gone

_Originally posted by @alikemaltanriverdi in https://github.com/EscherLabs/Graphene/issues/203#issuecomment-1061206413_

**Comment by Cloverstone** [comment]
temporary fix is to set the fields strict value to false under 'options'

**Comment by Cloverstone** [comment]
@alikemaltanriverdi can you confirm that this work around will fix the problem workflow?

**Comment by alikemaltanriverdi** [comment]
@Cloverstone it looks like it's fixing the problem, I was able to see the value in history.data.test.
Additionally, I'm not sure if we're going to be able to utilize this work around in a versioned workflow. I'd like to defer this decision to @timcortesi .

**Comment by alikemaltanriverdi** [comment]
@Cloverstone the issue seems to be resolved. You can close this issue anytime you'd like.
