### ISSUE TITLE
Adding new users does not check for duplicate, tries to add to DB

### ISSUE THREAD

**Issue by twhitney11** [EscherLabs/Graphene#21]
**Describe the bug**
When adding new user that already exists, it show success message, but DB error occurs in logs. The application should check if an existing user is already there rather than try to add and get unique constraint error in DB. Also, a message would be best displayed to indicate a duplicate. Furthermore, a 400 error should be returned from the API to indicate a problem with the request... for folks that user the API to add users rather than the GUI.

**To Reproduce**
1. Go to New -> User
2. Fill out all info and use an email address or unique id of another user
3. Click "Create"
4. See success message, but see error in log

**Expected behavior**
A clear error, and the application should not try to add the user if they already exist.

**Comment by twhitney11** [comment]
Thinking #22 will handle this. While we will likely be messing around with CAS, we noticed this issue when just adding users manually.

**Comment by timcortesi** [comment]
This has been addressed by @twhitney11 in 0c7e5b4.  Marking as closed.

Per above comment regarding CAS, a similar issue may need to be addressed in CAS authentication (specifically handle_saml and handle_generic functions of /app/Libraries/CASAuth.php) as an authenticating user with a new unique_id, but an email that already exists in the system will currently throw a generic authentication error.
