### ISSUE TITLE
Unauthenticated User Receives Error when Clicking Top Nav Public Page

### ISSUE THREAD

**Issue by twhitney2014** [EscherLabs/Graphene#212]
**Description**
We have a page in our default group that is public, so users do not need to login to it. When clicking the top level "Home" button we get a Laravel error indicating that "null" has no method "groups" because there is no authenticated user to get groups from.

**Feature / Subsystem**
Pages

**To Reproduce**
1. Create a public page that is home to a group
2. Navigate to the page when not authenticated
3. Click on the group name in the top nav

**Console Errors**
[2022-06-06 15:16:47] local.ERROR: Trying to get property 'groups' of non-object {"exception":"[object] (ErrorException(code: 0): Trying to get property 'groups' of non-object at /var/www/graphene/app/Http/Controllers/PageController.php:221)

**Comment by twhitney2014** [comment]
I have a proposed fix for this in PR #211

**Comment by Cloverstone** [comment]
pulled in PR #211
