### ISSUE TITLE
Creating an API function with no parameters results in no-name parameters in endpoint

### ISSUE THREAD

**Issue by acarter6134** [EscherLabs/Graphene#215]
# Expected Behavior

Routes created in Graphene with no parameters should produce endpoints with no parameters.

# Actual Behavior

Routes created in Graphene with no parameters produce endpoints with a single required parameter  with no name. See screenshot in step 6 of *To Reproduce*.

# To Reproduce
1. Create a new API by going to *APIs > New*.
2. Click on the new API, and create a new function with *Functions > New Function*. Have it return some string, like `return "hello";`

![function](https://user-images.githubusercontent.com/54380640/173874335-3d104c68-f699-44f6-802a-a49a25676490.png)

3. Create a new route with *Routes > New*, passing the name of the newly created function to *Function*. Do not create any parameters.

![route](https://user-images.githubusercontent.com/54380640/173874692-0628ca45-eb70-46e3-934c-6684c1255f3c.png)

4. Create a new API instance with *API Instances > New*, passing the newly created API to the API field.
5. In the API instances, add a user under *Permissions* and view the documentation by clicking the arrow near *Save*, then *View Documentation*
6. Despite not adding any parameters, the documentation indicates that the endpoint takes a single required parameter with no name.

![docs](https://user-images.githubusercontent.com/54380640/173875609-447f4500-52cb-4b89-872c-28c0bb1bc0a9.png)

7. Run `curl 'https://hostname/app/newFunction' -u user:pass`. It should return `hello` but instead returns `{"error":"You must provide: "}`
8. Run `curl 'https://hostname/app/newFunction/sometext' -u user:pass`. It returns `hello`

# Console Errors

The following warning appears when *New* is clicked in the *Routes* tab.

![warn](https://user-images.githubusercontent.com/54380640/173879517-7ad8308b-bab9-40b0-858e-e60175d691e4.png)

**Comment by timcortesi** [comment]
required parameters needs to be set to a min of 0.  I believe @Cloverstone already has a fix for this. Marking as high priority as this is impacting current API development
