### ISSUE TITLE
Clean install failing after last step of setup, missing workflows table

### ISSUE THREAD

**Issue by zhulb001** [EscherLabs/Graphene#23]
After following the installation video, my setup is failing after press save on the last set up page. It appears the workflow table was never created.

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'graphene.workflows' doesn't exist (SQL: select `id` from `workflows` where `site_id` = 1 and exists (select * from `workflow_developers` where `workflows`.`id` = `workflow_developers`.`workflow_id` and `user_id` = 1) and `workflows`.`deleted_at` is null) 

I noticed the last commit was related to workflows so maybe a issue was introduced then. Thanks.

**Comment by timcortesi** [comment]
Can you run "php artisan migrate" against the root directory? 

It sounds like you are missing a few of the workflow migrations.

-Tim

**Comment by zhulb001** [comment]
I'm receiving this Graphene]$ php artisan migrate

In Connection.php line 664:
                                                                               
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'graphene.workflo  
  w_submissions' doesn't exist (SQL: ALTER TABLE workflow_submissions MODIFY   
  `status` ENUM('open','closed','new') NOT NULL DEFAULT 'new';)                
                                                                               

In Connection.php line 458:
                                                                               
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'graphene.workflo  
  w_submissions' doesn't exist

**Comment by timcortesi** [comment]
I believe this is fixed... please confirm.

The 2019_010_01_000000_add_new_enum_to_workflow_submissions_table.php database migration had an extra "0" before the "10" in the file name, which was causing it to run out of order.  If you perform a git pull on the master branch and re-run "php artisan migrate" you should be all set.

**Comment by zhulb001** [comment]
Working fine now, thanks!
