### ISSUE TITLE
Graphene Workflows: Number field that cannot be set min to 0 

### ISSUE THREAD

**Issue by cankaturkmen** [EscherLabs/Graphene#238]
**Description**
The number field that set the min value to 0 fields can still be entered below 0 by clicking the down button that appears at the right of the number fields.

**Feature / Subsystem**
Graphene Workflows

**To Reproduce**

1. Create a "Number" field.
2. Click on down 'v' button that appears at the right of the number field.

**Link(s)**
https://my.binghamton.edu/admin/workflows/87

**Additional context**
![number_field_negative](https://user-images.githubusercontent.com/90630568/189988776-e8cafa11-93df-4f58-a451-a23b8da7571a.png)

**Comment by Cloverstone** [comment]
Looks like the value was not actually set to 0 - it was just the placeholder. If you set it to 0 it seems to work fine.
