### ISSUE TITLE
workflow object disappears when it has no name

### ISSUE THREAD

**Issue by alikemaltanriverdi** [EscherLabs/Graphene#24]
**Describe the bug**

**To Reproduce**
1. Go to 'workflows/..#options'
2. Click on 'Add component'
3. Delete the default name
4. All box disappears and doesn't come back

**Expected behavior**
Box to show up when a new name is written

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6 (18G103)
 - Browser: Chrome
 - Version: 77.0.3865.90 (Official Build) (64-bit)

**Comment by timcortesi** [comment]
Workflow "states" with no name disappear from view (along w/ other stuff).  It should probably be impossible to have a workflow state with a name less than a single character, or create some other internal name mapping mechanism that prevents the behavior.

**Comment by timcortesi** [comment]
I believe this has been fixed.  @Cloverstone can you confirm?

**Comment by Cloverstone** [comment]
yes - this has been fixed

**Comment by timcortesi** [comment]
Confirmed Fixed in caf8fd9
