### ISSUE TITLE
Two fields on CAS configuration tab don't populate correctly

### ISSUE THREAD

**Issue by timroberson** [EscherLabs/Graphene#3]
**Describe the bug**
If you change CAS Enable SAML to Disabled, save, and then return to the form, CAS Enable SAML is populated with Enabled even though the value is correct in the database. The same exact issue happens with External User Lookup Enabled.

**To Reproduce**
1. Go to a site's CAS configuration tab
2. Change CAS Enable SAML to Disabled
3. Save
4. Refresh the page
5. Go back to the CAS configuration tab

**Expected behavior**
CAS Enable SAML is populated with Disabled

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser: Firefox
 - Version: 65.0.1 (64-bit)

**Comment by timcortesi** [comment]
Good find -- this is a byproduct of the way boolean values (true/false) are sent as form values from the browser to the server.  I switched these to string values ("true"/"false"), which corrects the issue.
