### ISSUE TITLE
Graphene Forms: Callstack Exceeded

### ISSUE THREAD

**Issue by timcortesi** [EscherLabs/Graphene#30]
**Description**
Callstack exceeded when duplicate options sections with conditions created
caused by event cycle on "type"

**Feature / Subsystem**
Graphene Forms

**To Reproduce**
1. Add options type
2. Add conditions to options set
3. Duplicate options set
4. Add conditions to second set

**Console Errors**
Callstack Exceeded

**Additional context**
NOTE: this is not new and is in the currently public code as well

**Comment by Cloverstone** [comment]
This is fixed
