### ISSUE TITLE
Workflow File Upload Returns 404

### ISSUE THREAD

**Issue by timcortesi** [EscherLabs/Graphene#31]
**Description**
When uploading a file to form of a workflow, it doesn't complete the upload and returns 404 error in the console.
File upload would not be successfuly completed unless you refresh the page. When the page is refreshed, it can be seen that the file was uploaded at the first time

**Feature / Subsystem**
What Graphene feature or subsystem does this pertain to?  (Examples: Workflows, MicroApps, Forms, Data Grids, API Gateway, etc)

**To Reproduce**
1. Open a freshly new workflow
2. Drag and drop a file in the file upload part
3. Indicator on the file doesn't change to check mark
4. When you refresh the page and try it again, it starts to work and can see the uploaded file

**Console Errors**
1. Uncaught TypeError: Cannot read property 'files' of null
2. Failed to load resource: the server responded with a status of 404 (Not Found)

**Link(s)**
https://my.binghamton.edu/workflow/workflows_dev/rf_boa_monthly_recon_new

**Comment by timcortesi** [comment]
Comments from @Cloverstone:

Can't reproduce in any other form - though does seem to happen on that exact form.
Exporting and importing it locally however does not reproduce the problem

**Comment by Cloverstone** [comment]
fix in workflow branch - 611e6e1

**Comment by timcortesi** [comment]
Tested and working in 0697d48
