### ISSUE TITLE
Workflows: OnEnter and OnLeave tasks being intermixed

### ISSUE THREAD

**Issue by timcortesi** [EscherLabs/Graphene#33]
**Description**
"Tasks" which are set for "On Enter" end up applied to "On Leave"

**Feature / Subsystem**
Workflows

**To Reproduce**
1. Click on the "processing" state
2. Add an "On Enter" task to the "processing" state (
2a -- "email" seems to work fine, don't necessarily need to fill in the rest of the fields.
3. Click the little blue "check" box 
4. Click on the "processing" state and look at the tasks associated with "On Leave"
5. Note that the same task applied to "On Enter" is now also applied to "On Leave"

**Link(s)**
https://my.binghamton.edu/admin/workflows/14#options

**Additional context**
Note that this also happens in reverse -- delete the on enter task also deletes the on leave tasks.

**Comment by Cloverstone** [comment]
fix in workflow branch - 611e6e1

**Comment by timcortesi** [comment]
confirmed fixed in 0697d48
