### ISSUE TITLE
Workflow Tasks: "Email" Needs to be fleshed out

### ISSUE THREAD

**Issue by timcortesi** [EscherLabs/Graphene#35]
On Tasks, when sending an email, you should be able to specify a user or a group ID (same as with assignment).  This should be dynamically configurable to include owner, assigned to, form fields, etc.  

I think some of this is implemented partially, but this needs to be cleaned up a bit and better fleshed out.

**Comment by Cloverstone** [comment]
add resource and form users to the email->to field in tasks

**Comment by timcortesi** [comment]
Missing defaults for "Owner" and "Actor".  Note differences below between Assignment options vs Email options.

(Should just be {{owner.email}} and {{actor.email}})

<img width="341" alt="Screen Shot 2020-07-28 at 1 33 07 PM" src="https://user-images.githubusercontent.com/5395437/88700631-f928c980-d0d6-11ea-8dae-8ea91bf05e7c.png">
<img width="323" alt="Screen Shot 2020-07-28 at 1 33 20 PM" src="https://user-images.githubusercontent.com/5395437/88700632-f928c980-d0d6-11ea-81da-f44decc085cc.png">

Reassigning back to @Cloverstone

**Comment by Cloverstone** [comment]
fixed in 7fdd0a7

**Comment by timcortesi** [comment]
This doesn't look right... value should be `{{owner.email}}`, instead seeing "User that initiated the workflow" as the value in the workflow definition.  See Excerpt from workflow definition below:

Looks like this...
```javascript
{
"to": [
"User that initiated workflow"
],
"task": "email",
"content": "{{owner.first_name}} {{owner.last_name}} - ..."
}
```

Should look like this...
```javascript
{
"to": [
"{{owner.email}}"
],
"task": "email",
"content": "{{owner.first_name}} {{owner.last_name}} - ..."
}
```

Assigning to @Cloverstone

**Comment by Cloverstone** [comment]
I just copied from the other use of this but it looks like this is why we didn't implement this sooner - we don't have the emails for form.users or resource users - we only have unique_id which is what we use in all of the other cases. I will look into what it will take to do emails for this one

**Comment by timcortesi** [comment]
Confirmed working in 650a3f9
