### ISSUE TITLE
Workflows: Add third tab for "my history"

### ISSUE THREAD

**Issue by timcortesi** [EscherLabs/Graphene#41]
Add a third tab that allow users to see a list of workflow that they have previously interacted with.  (This is separate from workflows for which they have a current assignment)

https://my.binghamton.edu/workflows

Maybe.. my history?

**Comment by timcortesi** [comment]
Comment from @Cloverstone 

> this will make more sense when we switch to pages instead of tabs - otherwise we will be making a lot of unnecessary queries

Agreed... should make workflows tabs native

**Comment by timcortesi** [comment]
Now that workflows exist in multiple tabs, has this tab been added?

**Comment by Cloverstone** [comment]
yes it has been added, it needs the query to be written (that was why you were assigned - you said you would write that), should be visible in any commit following the one referenced earlier 
54d1605

**Comment by timcortesi** [comment]
Implemented and working in 4eb6fac
