### ISSUE TITLE
Need ability to export a list of members from a group (CSV)?

### ISSUE THREAD

**Issue by timcortesi** [EscherLabs/Graphene#45]
ETS regularly tries to email all members and needs a list of everyone who is a member of that group in myBinghamton.  There is currently no way to do this.  Currently I log into the database and run some SQL:

```sql
select email from users 
left join group_members on users.id = group_members.user_id
where group_id = 30;
```

An "export members" button or something would be great.

Note that when a group has over 500 users, I think we only return a subset of them here.  It's kind of weird and probably wrong.  There's actually 1261 members, but we only show 463 of them.  That might be a bug?  I don't remember why I did that.
https://my.binghamton.edu/admin/groups/30
vs...
https://my.binghamton.edu/admin/groups/30/members

Assigning to Adam to provide thoughts

**Comment by Cloverstone** [comment]
I added this functionality as csv with unique_id, first_name, last_name, and email fields included - this could be made customizable as well as the file time in the future but i think this provides the necessary functionality

**Comment by timcortesi** [comment]
Tested and working in 0697d48
