### ISSUE TITLE
Redo the /Admin/Users Page

### ISSUE THREAD

**Issue by timcortesi** [EscherLabs/Graphene#46]
The old /admin/users page works fine, but needs an overhaul.  Should probably use GrapheneForms with smallcombo for user search.  

https://my.binghamton.edu/admin/users

This is probably closer to what we should build: (From the BComply System)
http://bcomplydev.binghamton.edu/admin/users

**Comment by alikemaltanriverdi** [comment]
@timcortesi I believe that this issue can now be resolved after the most recent updates in Graphene

**Comment by timcortesi** [comment]
Marking this as closed/complete
