### ISSUE TITLE
Graphene

### ISSUE THREAD

**Issue by timcortesi** [EscherLabs/Graphene#48]
If the first page/app/workflow/whatever in a group (as defined by the "sort" order) is unlisted, it should not be the page/app/workflow/whatever that is navigated to when you visit the group.

For example:

For Group "TEST" which has 2 pages:
* Page 1 <-- page 1 is unlisted
* Page 2 

When you navigate to /page/test, it should redirect you to /page/test/page2, not /page/test/page1. 
Current behavior navigates to page 1.  quick fix is to change the order of the pages so page 2 is sorted before page 1.

**Comment by Cloverstone** [comment]
i thought this was intentional?
case one - you don't want that behavior just move it to another position in the order, after the first listed one
case two  - you do want the group home page to show first  but not be listed in the menu - use this option

or am i misunderstanding the effect? or missing a major downside?

**Comment by timcortesi** [comment]
Lauri had a situation today where she had an app that was the only app in a group (no pages)
https://my.binghamton.edu/admin/groups/164/appinstances
She wanted to hide that app, and then instantiate a new app (which we did)
Then, when she navigated to the app from the menu, it looked like it was showing the new app (the only app for which there was a menu), but actually it was showing the hidden app.
I ended up changing the sort order, and that fixed the isssue, but she was confused.  
It seems to me that we should redirect you to the first non-unlisted (listed?) app/page/workflow.  Having you be automatically redirected to content which is unlisted doesn't seem right.

**Comment by Cloverstone** [comment]
I don't feel super strongly here but I would say that this seems to take flexibility away, and the use case seems a little misplaced and may be better served by having an "active" flag or date range or something similar to actually turn an app off. If you just un-list it you can still go to an unlisted app and the purpose seems to be more of deprecating or disabling an unused app.

**Comment by timcortesi** [comment]
Alright.  Closing as the current behavior is as designed.
