### ISSUE TITLE
Section in form builder being renamed

### ISSUE THREAD

**Issue by Cloverstone** [EscherLabs/Graphene#52]
**Description**
When there are multiple sections - sometime when switching between them or saving one will be renamed as the other

**Feature / Subsystem**
Graphene - form builder in microapps/workflows

**To Reproduce**
Not sure of exact steps but it definitely happens and I don't want it to be forgoten

**Comment by alikemaltanriverdi** [comment]
I just added the screen recording for a way to duplicate this bug. You can find the link below:

https://drive.google.com/drive/folders/1t2xOYn2AUOUfVqWgYGH5WIeB4lqnW6D6?usp=sharing

**Comment by Cloverstone** [comment]
This is a completely different bug - will look at it though

**Comment by timcortesi** [comment]
#79 is still an issue, but I have not seen this in months.  Closing
