### ISSUE TITLE
Workflow: Dashboard is not showing workflows

### ISSUE THREAD

**Issue by alikemaltanriverdi** [EscherLabs/Graphene#61]
**Description**
In notification page, workflow dashboard is neither showing "My Current Assignments" nor "My Workflows" 

**Feature / Subsystem**
Graphene / Workflows

**To Reproduce**
1. Delete a workflow that is assigned to me
2. Go to Notifications Page
3. Observe that my workflows and my assignments tabs have no record in them.

**Console Errors**
Uncaught TypeError: Cannot read property 'name' of null
    at flow.cob.js?cb=9:661
    at l (lodash.min.js?cb=9:6)
    at Function.uu (lodash.min.js?cb=9:67)
    at flow.cob.js?cb=9:661
    at new gform.mapOptions (gform_bootstrap.min.js?cb=9:1)
    at gform.mapOptions.<anonymous> (gform_bootstrap.min.js?cb=9:1)
    at l (lodash.min.js?cb=9:6)
    at Function.uu (lodash.min.js?cb=9:67)
    at gform.mapOptions.o (gform_bootstrap.min.js?cb=9:1)
    at new gform.mapOptions (gform_bootstrap.min.js?cb=9:1)

**Link(s)**
https://my.binghamton.edu/workflows

**Additional context**
See the attached screenshots in order to have a better understanding of the error
<img width="1273" alt="Screen Shot 2020-04-16 at 10 13 29 AM" src="https://user-images.githubusercontent.com/11221504/79472081-65246d80-7fd1-11ea-8709-9c81ab0d57f5.png">
<img width="1667" alt="Screen Shot 2020-04-16 at 10 15 59 AM" src="https://user-images.githubusercontent.com/11221504/79472103-6b1a4e80-7fd1-11ea-825b-de497ac7f108.png">

**Comment by alikemaltanriverdi** [comment]
@Cloverstone Please see the description of the issue above

**Comment by timcortesi** [comment]
When we run these queries, we need to be running "withTrashed" on workflows / workflow_instances, to take into account workflows / workflow_instances which may have been soft deleted.  

Additionally, we really should implement some sort of garbage collection to allow for the deletion of zombie submissions related to soft deleted workflows and workflow instances.

**Comment by timcortesi** [comment]
I believe this has been fixed.
