### ISSUE TITLE
Random Issues Related to Workflow Resources

### ISSUE THREAD

**Issue by timcortesi** [EscherLabs/Graphene#62]
I'm out tomorrow morning, and I built this (which mostly works):
http://portalawsdev.binghamton.edu/workflow/152/spring2020_grade_option_change_request_dev
But I found some random issues, so i'm listing them all here:

1. The owner object doesn't appear to be passed when fetching resources, so adding {{owner.unique_id}} to the route doesn't work right.  For the time being, I have the bnumber hard coded.  **NOTE: {{user.unique_id}} DOES work, but that's not actually useful or correct for this particular workflow.**  I need the bnumber of the submitter, not the currently authenticated user.
http://portalawsdev.binghamton.edu/admin/workflows/25#resources
<img width="613" alt="Screen Shot 2020-04-28 at 11 24 05 PM" src="https://user-images.githubusercontent.com/5395437/80558200-814be580-89a7-11ea-921f-56d00e84fd3c.png">

2. "edit":false doesn't seem to work for "selects" in form fields.  Note that "locked", "current grade mode" and other fields are set to "edit":false, and they are still editable.
http://portalawsdev.binghamton.edu/workflow/152/spring2020_grade_option_change_request_dev
<img width="766" alt="Screen Shot 2020-04-28 at 11 26 34 PM" src="https://user-images.githubusercontent.com/5395437/80558261-ba845580-89a7-11ea-9ba6-1e99269bc608.png">

3. Take a look at "courses.current_grade_mode" in the form builder.  The Conditions are all wonky, with edit, show.. etc all displaying something that looks like this... and it's throwing some error.  
http://portalawsdev.binghamton.edu/admin/workflows/25#forms
<img width="480" alt="Screen Shot 2020-04-28 at 11 29 54 PM" src="https://user-images.githubusercontent.com/5395437/80558399-3d0d1500-89a8-11ea-8aa4-0be32a86f548.png">
<img width="300" alt="Screen Shot 2020-04-28 at 11 28 22 PM" src="https://user-images.githubusercontent.com/5395437/80558400-3e3e4200-89a8-11ea-8acf-92711663e1ea.png">

4. I think I had a situation where the form didn't update after I clicked the blue check box, and I had to go back and do it again.  But I tried 3 times to replicate the issue, and wasn't able to do so.  So maybe it was nothing.

I think that's it for now.

**Comment by timcortesi** [comment]
5. One more thing.. After I submit the workflow, if I go back to it again, the form is empty (doesn't auto-populated with the external resource info).  (See attached image)  If I then refresh the page, everything is populated as expected.  I'm guessing that populating the form w/ external resources only works if the form is already started.

<img width="833" alt="Screen Shot 2020-04-28 at 11 44 42 PM" src="https://user-images.githubusercontent.com/5395437/80559042-6169f100-89aa-11ea-82e4-92c6b3a25eed.png">

**Comment by Cloverstone** [comment]
It looks like the first one works, its not {{users.unique}} though its {{user.unique_id}}

**Comment by timcortesi** [comment]
Confirmed Fixed
