### ISSUE TITLE
Hide "unlisted" workflows from generic "workflows" widget

### ISSUE THREAD

**Issue by timcortesi** [EscherLabs/Graphene#66]
Currently, all available workflows are visible within the "workflows" widget.  We really should only be displaying workflows that are not "unlisted"

https://my.binghamton.edu/workflows

This will need to be updated so we don't accidentally advertise workflow availability that should not be advertised.

**Comment by Cloverstone** [comment]
completed in 4cf4b3e (forgot to tag)
