### ISSUE TITLE
Creating group with slug of previously deleted group causes internal server error

### ISSUE THREAD

**Issue by timroberson** [EscherLabs/Graphene#72]
**Description**
I tried to create a group with the slug of a group I previously deleted. I expect to be able to re-use the slug or, at the very least, see a message informing me that I can't use the slug.

**Feature / Subsystem**
Groups

**To Reproduce**
1. Create a group
2. Delete the group created in step 1
3. Create a group using the same slug used in step 1

**Console Errors**
Not from the console, but here's the message from the PHP exception:

> SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'mygroup' for key 'groups_slug_unique' (SQL: insert into `groups` (`name`, `slug`, `site_id`, `updated_at`, `created_at`) values (My Group, mygroup, 1, 2020-05-26 10:35:02, 2020-05-26 10:35:02))

**Comment by timcortesi** [comment]
Looks like an issue w/ soft deletes.  Will nee to consider how best to handle this.  Possible nullify slug when deleting groups?

**Comment by timcortesi** [comment]
Looking at this again, there really shouldn't be a uniqueness constraint on group slugs
```php
$table->string('slug')->unique();
```

Need to add another migration that drops that constraint.

**Comment by timcortesi** [comment]
Fixed in bbc4a58

Will need to re-run `php artisan migrate`
