### ISSUE TITLE
Graphene Forms Checkbox "display" not visible

### ISSUE THREAD

**Issue by timcortesi** [EscherLabs/Graphene#76]
If I create a checkbox with "display" text, that value is not displayed on the form itself when I click "View" or just browse to the form.  It does show up as expected in the form builder, however.  (Note the two different attachments where the text is displayed / not displayed)

An example is here: https://my.binghamton.edu/admin/workflows/18

```json
{
					"type": "checkbox",
					"label": "This travel is essential for university business",
					"name": "is_essential",
					"display": "This text is not displayed",
					"value": false,
					"help": "The traveler understands that they must abide by all health and safety protocols.  \n<br>Visit: <a href=\"https://www.binghamton.edu/restarting-binghamton/frequently-asked-questions.html\">Restarting Binghmton Frequently Asked Questions</a> for more information",
					"required": true,
					"options": [
						{
							"value": false
						},
						{
							"value": true
						}
					]
				},
```

<img width="654" alt="Screen Shot 2020-07-08 at 2 40 14 PM" src="https://user-images.githubusercontent.com/5395437/86957772-324dc980-c129-11ea-963b-0bc93d2220f2.png">
<img width="442" alt="Screen Shot 2020-07-08 at 2 40 25 PM" src="https://user-images.githubusercontent.com/5395437/86957773-337ef680-c129-11ea-8064-8eef10cb5a16.png">

**Comment by Cloverstone** [comment]
That is not a bug - the field was only left in there because some people had used it. The proper way to have values there is to have labels on the options

**Comment by timcortesi** [comment]
Once I configure options, I end up with "true" and "false" (strings) as the values.  Is there any way to have a label while retaining true and false (not strings) as the values?

**Comment by Cloverstone** [comment]
yeah leave them empty

**Comment by Cloverstone** [comment]
looks like i am getting undefined - i specifically had that working for
lauri at one point

**Comment by Cloverstone** [comment]
i believe you can delete them and until you edit it again its still empty -
i will look into it though

**Comment by timcortesi** [comment]
If I delete the "undefined" values, I get this ...
```json
"options": [
{
  "label": "I agree"
},
{
  "label": "I do not agree"
}
]
```
That just keeps it as "I agree", however and doesn't toggle back/forth
