### ISSUE TITLE
Graphene Workflows: Switching Tabs while Editing Workflow Form Breaks Things

### ISSUE THREAD

**Issue by timcortesi** [EscherLabs/Graphene#79]
@alikemaltanriverdi just added the screen recording for a way to duplicate this bug. You can find the link below:

https://drive.google.com/drive/folders/1t2xOYn2AUOUfVqWgYGH5WIeB4lqnW6D6?usp=sharing

Workflow Link: https://my.binghamton.edu/admin/workflows/8#forms

**Comment by timcortesi** [comment]
This is still an issue in latest binghamton-prod release.  Marking this as a priority. @alikemaltanriverdi can provide additional insight and example conditions if required.

**Comment by alikemaltanriverdi** [comment]
@Cloverstone is there any update on this? If you need anything from me, I'd be happy to provide clarifications or additional documents.

**Comment by Cloverstone** [comment]
There is no update - I have not been able to identify what causes it yet -
I don't have an estimate on time to fix it for this reason either.

**Comment by timcortesi** [comment]
Assigning to @alikemaltanriverdi to test in http://portalawsdev.binghamton.edu
