### ISSUE TITLE
Workflows: Workflow Editor "Action" label loses focus after first character is entered

### ISSUE THREAD

**Issue by timcortesi** [EscherLabs/Graphene#82]
When creating a new "Action" on a Workflow State, the first character typed into the "Label" field causes the label field to lose focus.  The user can then refocus on the "Label" field and continue typing.  

When the "Label" field is empty, there is no "Name" field -- I'm guessing that has something to do with it, but I'm also not sure why there can't always be a "Name" field?  It seems to me that a "Label" field and a "Name" field are always required, so I'm not entirely sure why the "Name" field is hidden until the "Label" field has something in it.  

Regardless, while not a huge issue, this is kind of annoying.  I'm not sure what, if any resolution exists.  

<img width="403" alt="Screen Shot 2020-07-30 at 1 15 51 PM" src="https://user-images.githubusercontent.com/5395437/88953818-75521700-d267-11ea-9529-c4b20cca3cb5.png">
<img width="411" alt="Screen Shot 2020-07-30 at 1 16 00 PM" src="https://user-images.githubusercontent.com/5395437/88953822-75eaad80-d267-11ea-99e8-7b310da73f57.png">

**Comment by timcortesi** [comment]
@Cloverstone It looks like this behavior has been changed, and that this is no longer an issue in the latest binghamton-prod code.  Can you confirm that this is fixed?

**Comment by Cloverstone** [comment]
Yes, this is fixed

**Comment by timcortesi** [comment]
Marking this as closed / completed.
