### ISSUE TITLE
Graphene Micro App User Options Aren't Validated

### ISSUE THREAD

**Issue by timcortesi** [EscherLabs/Graphene#88]
When setting Micro App User Options using the built-in functionality, it is possible to click "Save" and submit the user options without providing all required fields.  

I am guessing that a validation check isn't being run before options are updated.

<img width="104" alt="Screen Shot 2020-08-28 at 11 12 25 AM" src="https://user-images.githubusercontent.com/5395437/91583594-738b7a00-e91f-11ea-9b32-8932a0e80c34.png">

**Comment by timcortesi** [comment]
Assigning to @alikemaltanriverdi to test in http://portalawsdev.binghamton.edu

**Comment by alikemaltanriverdi** [comment]
User options those open in a pop-up window works as expected and can only be submitted when they're not empty
<img width="660" alt="Screen Shot 2020-12-30 at 4 50 01 PM" src="https://user-images.githubusercontent.com/11221504/103383049-4b737980-4abf-11eb-80c1-4abec88dfc9d.png">


I can still save an app instance even both options and user options are empty but required fields. Please see the screenshot below for a better understanding.

<img width="1474" alt="Screen Shot 2020-12-30 at 4 52 03 PM" src="https://user-images.githubusercontent.com/11221504/103383068-5e864980-4abf-11eb-90d6-695bb64478d5.png">

**Comment by timcortesi** [comment]
Assigning to @Cloverstone to review feedback.  

It appears that @alikemaltanriverdi has identified a second behavior similar to, but different from what is outlined in the original bug report.  With that said, if we can address this second bug without writing up a new bug report, that would save me some time.
