### ISSUE TITLE
Modal "footer" class

### ISSUE THREAD

**Issue by timcortesi** [EscherLabs/Graphene#9]
In the User Options Modal, there appears to be a nested div with a "footer" class.  While this may not be a global issue, it appears to be colliding with Binghamton University specific CSS.  Can this div be renamed to something more specific?
```
<div class="modal-content">
<div class="modal-footer gform-footer">
<div class="footer"></div>
```
<img width="608" alt="Screen Shot 2019-05-10 at 12 50 24 PM" src="https://user-images.githubusercontent.com/5395437/57543655-f64f8680-7322-11e9-9a7a-8a76e7a9faa9.png">

**Comment by Cloverstone** [comment]
removed .footer

**Comment by Cloverstone** [comment]
footer removed - not used
