### ISSUE TITLE
Multiple "Named" Unsubmitted workflows?

### ISSUE THREAD

**Issue by timcortesi** [EscherLabs/Graphene#93]
We've received multiples of the following 2 requests (or similar):

* I'd like the ability to have multiple in-progress unsubmitted workflows open at the same time and be able to switch between them.
* I'd like to be able to name my submissions and reference back to them in the "My Workflows" view.

We may be able to address both of these together in some capacity.  

Additional context from Amber...
> Based on the question I believe the departments would fill out multiple forms for different students, then complete those when the requirements have been met.  Sounds like that is not possible.  A meeting is a good idea.  
> 
> Thanks,
> Amber 

More context for the naming feature from Julian...
> I have a suggestion for the electronic RF Payment Request/Reimbursement form, from an end-user perspective. It would be extremely helpful if there was a “Title” field at the top of the form where we could enter a descriptive title of the request. For example, if I could enter “Reimbursement for John Smith, October 22, 2020” as a title, it would be incredibly helpful when searching for a particular reimbursement in “My Workflow.”  As it is now, when someone asks me to check the status on their reimbursement, I have to open every single entry in my workflow until I can find the one I am looking for.

**Comment by timcortesi** [comment]
Bumping this to "high priority"

**Comment by Cloverstone** [comment]
@timcortesi Do we want a title field in the database for this - or should we just add it to the data field. It feels like it deserves its own place to me but I don't feel strongly.

**Comment by timcortesi** [comment]
@Cloverstone Yeah, I think I agree.  This probably requires a new column in the `workflow_submissions` table which stores an optional (nullable) `description` field.  Probably best to keep the `data` field limited to form data.

**Comment by timcortesi** [comment]
These changes exist on the `binghamton-prod` branch.  Once merged back into the `bingahmton-staging` branch, these changes can be reviewed / tested.
