### ISSUE TITLE
Workflows: Option to SKIP validation on certain actions.  (Due 12/7/2020)

### ISSUE THREAD

**Issue by timcortesi** [EscherLabs/Graphene#95]
There are certain actions where we don't actually want to perform any validations (specifically checking for required fields).  In those situations, we want to be able to bypass the validations.

**Comment by timcortesi** [comment]
This is completed and is in test.

**Comment by timcortesi** [comment]
@alikemaltanriverdi please test this in portalawsdev

**Comment by alikemaltanriverdi** [comment]
Skip validation feature works as expected. Tested in portalawsdev.

**Comment by timcortesi** [comment]
Marking as closed / complete.

**Comment by timcortesi** [comment]
@Cloverstone Did we anticipate needing to bypass validations in situations other than the initial submission?  Per @alikemaltanriverdi it sounds like those additional situations are not implemented.  The initial description was not clear, so this is left up to interpretation.

**Comment by Cloverstone** [comment]
Ok, I will look into it - I don't recall if it was implemented on other
submissions but I thought it was

**Comment by Cloverstone** [comment]
Ok - so I just looked and it seems to work on any action regardless of
state - however if a signature is required - then you still need the
signature to submit (even with erros). Can you confirm this behavior,
because this seems right from my perspective.

**Comment by alikemaltanriverdi** [comment]
Yes, this is correct. 
1. I have tested it on a couple workflows in portalawsdev and it was allowing me to submit the workflow once I signed it even with errors on the form. 
2. When I removed "Require Signature" condition from the action, I was able to submit the form without required fields. 
3. The initial case (not being able to submit a form if "Allow Invalid Submission" is not selected) also works as expected.

**Comment by timcortesi** [comment]
The behavior as described is by design.  "Requiring a signature" supersedes all other validation constraints.  If a signature is required on a form which does not require validation, those actions should be separated into something like: "Save for Later" and "Sign / Submit".  

Marking this as closed / complete.
