### ISSUE TITLE
GrapheneForms: Smallcombo allows limited interactivity when "enabled":false

### ISSUE THREAD

**Issue by timcortesi** [EscherLabs/Graphene#98]
It appears that there remains some limited interactive functionality on "smallcombo" form fields even when "enabled" is set to false.  

See the attached example.  In that situation, there is a "file" type which, when the down arrow is clicked, allows some limited interaction.  You can't actually change the value, but it has lead to some user confusion thinking that the field is in fact editable (when it is not).

<img width="256" alt="Screen Shot 2020-12-15 at 4 56 52 PM" src="https://user-images.githubusercontent.com/5395437/102277756-bd13cb00-3ef6-11eb-925d-85529f0797af.png">

Here's another example of a normal smallcombo which is not editable:

<img width="734" alt="Screen Shot 2020-12-15 at 4 59 47 PM" src="https://user-images.githubusercontent.com/5395437/102277955-fc421c00-3ef6-11eb-94de-70143efa54af.png">

**Comment by alikemaltanriverdi** [comment]
The same behavior is also valid for the User type fields. Please see the additional comments below:

**Description**
These bugs are currently in the production.

When a SmallCombo type and User type field are set as not-editable field in their conditions, they're still editable field and they look like enabled fields. If the section that has smallcombo box or user in it is set as a non-editable, then they both look like disabled, such as a non-editable hover item, etc, but they can be selected, edited, etc.

**Feature / Subsystem**
This is in the form of the workflows.

**To Reproduce**
1. Go to a workflow or an app, such as https://my.binghamton.edu/admin/workflows/57 , https://my.binghamton.edu/admin/apps/278
2. Select a user type field and smallcombo type field and set "Editable" condition to "Never" or some other condition.
3. Save the workflow/ app and go to app/ workflow to observe.
4. Go to form builder of the workflow one more time to make condition of the "Edit" of the section they are located into "Never" and observe the form. 

**Console Errors**
None

**Link(s)**
1. Open the DEV instance of the following workflow that is in Workflow(Dev) group: https://my.binghamton.edu/admin/workflows/57
2. https://my.binghamton.edu/admin/apps/278

**Additional context**
**Workflow form example:**
<img width="978" alt="Screen Shot 2021-03-25 at 5 49 34 PM" src="https://user-images.githubusercontent.com/11221504/112548367-7ace1580-8d92-11eb-93e3-e0e8552ec6db.png">
Note: In the screenshot above: **Student**: User type field that has edit condition as "if _flowstate -> not matches -> origin or Save For Later"
**Degree and Program**: Smallcombo type field that has edit condition as "if ->_flowstate -> not matches -> origin or Save For Later" I also tried changing the condition to "Never" but it was acting the same.
**App form example:**
<img width="1639" alt="Screen Shot 2021-03-25 at 6 04 34 PM" src="https://user-images.githubusercontent.com/11221504/112549701-963a2000-8d94-11eb-8dd6-4256c92eae7c.png">

If you need additional links/ explanation, you can contact to me @alikemaltanriverdi

**Comment by timcortesi** [comment]
@Cloverstone -- Are you able to "fix" this issue in Graphene without doing a full patch to the underlying gform library?  We're having issues with this, as effectively any combobox in any workflow is editable, even when it appears that it is not.  We have a couple workflows which will require this to be addressed in the next couple weeks. (April 15th)

**Comment by Cloverstone** [comment]
I have had a fix in development for a while - I will look into the
possibility of it being a stand alone patch.

**Comment by timcortesi** [comment]
@Cloverstone yeah -- that's what I had thought, but a standalone patch would be great given the current reality.  thanks.

**Comment by alikemaltanriverdi** [comment]
@Cloverstone it seems like this issue had been resolved, you can close this issue anytime you'd like. I just tested it in the production, and it was behaving as expected for both the workflows and the microapps
