### ISSUE TITLE
When versioning on Hermes, version date is wrong

### ISSUE THREAD

**Issue by nwallin1** [EscherLabs/Graphene#99]
**Description**
When creating a new version of an API on Hermes, the date that the version displays is not the date that the I created the version.
Ex: I create a new version on 12/15/2020. It says that the version was created on 11/30/2020
**Feature / Subsystem**
API Gateway (Hermes)

**To Reproduce**
Steps to reproduce the behavior.  
1. Go to any API on Hermes.
2. Version the API
3. Check the date the API was versioned, can do this in an API instantiation

![image](https://user-images.githubusercontent.com/32525511/102286664-c60c9880-3f06-11eb-94fa-d29c32e599c1.png)

**Comment by timcortesi** [comment]
This was implemented in: https://github.com/EscherLabs/GrapheneAPIGateway/commit/7f33799249538b91252ec6bada47b72bfe809358

Marking this as closed/complete.
